# This is a config for E2B sandbox template.
# You can use template ID (esi4plzztc3bq0txrysw) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("esi4plzztc3bq0txrysw") # Sync sandbox
# sandbox = await AsyncSandbox.create("esi4plzztc3bq0txrysw") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('esi4plzztc3bq0txrysw')

team_id = "3d922d3f-cca1-419a-876e-cf845ca61a3b"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "esi4plzztc3bq0txrysw"
