name: lint
on:
    push:

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [20]

        steps:
        - uses: actions/checkout@v4
        - name: Install bun
        uses: bun/action-setup@v4
        with:
            version: 9

        - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'bun'
        - name: Install dependencies
            run: bun install
        - name: Run lint
            run: bun lint